# -*- coding: utf-8 -*-

import os
import shutil
import sys
import build.dpkg

arch = ARGUMENTS.get('arch', 'amd64')

DEBNAME          = "neoagent"
DEBVERSION       = "0.7.1"
SUBVERSION       = "1"
DEBMAINT         = "Tatsuhiko Kubo [cubicdaiya@gmail.com]"
DEBARCH          = arch
DEBDEPENDS       = "libev-dev, libjson0-dev, libgoogle-perftools-dev, python-argparse"
DEBDESC          = "A Yet Another Memcached Protocol Proxy Server"
DEBCONTROLFILE   = os.path.join(DEBNAME, "DEBIAN/control")
DEBCOPYRIGHTFILE = os.path.join(DEBNAME, "DEBIAN/copyright")
DEBCHANGELOGFILE = os.path.join(DEBNAME, "DEBIAN/changelog")

DEBFILES = [
    # TODO: generate following tupples
    ("usr/bin/neoagent",                 "neoagent/neoagent"),
    ("usr/bin/neostat",                  "misc/neostat/neostat"),
    ("usr/bin/neoctl",                   "misc/neoctl/neoctl"),
    ("usr/share/doc/neoagent/copyright", "debian/copyright"),
    ("usr/share/doc/neoagent/changelog", "debian/changelog"),
    ("usr/share/man/man1/neoagent.1",    "doc/build/man/neoagent.1"),
    ("usr/share/man/man1/neostat.1",     "doc/build/man/neostat.1"),
    ("usr/share/man/man1/neoctl.1",      "doc/build/man/neoctl.1"),
]

build.dpkg.make_package(Environment(),
                        DEBNAME,
                        DEBVERSION,
                        SUBVERSION,
                        DEBMAINT,
                        DEBARCH,
                        DEBDEPENDS,
                        DEBDESC,
                        DEBCONTROLFILE,
                        DEBCOPYRIGHTFILE,
                        DEBCHANGELOGFILE,
                        DEBFILES)
